services:
  backend:
    build: .
    ports:
      - "3000:3001" #* 3000 because this is the logger server all others connect to
    command: npm run dev_docker
    volumes:
      - "./src:/app/src" #! Not readonly.   Avoid it if you plan on using prisma which generates the client in the src folder. 